# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
name: "App Center"
description: "GitHub Action that uploads artefacts for Visual Studio App Center"
author: "Wojciech Zięba <@wzieba>"
inputs:
  appName:
    description: "App name followed by username e.g. wzieba/Sample-App"
    required: true
  token:
    description: "Upload token - you can get one from appcenter.ms/settings"
    required: true
  group:
    description: "Distribution group"
    required: true
  file:
    description: "Artefact to upload (.apk or .ipa)"
    required: true
  buildVersion:
    description: "Build version parameter required for .zip, .msi, .pkg and .dmg files"
    required: false
  buildNumber:
    description: "Build number parameter required for macOS .pkg and .dmg files"
    required: false
  releaseNotes:
    description: "Release notes visible on release page"
    required: false
  gitReleaseNotes:
    description: "Generate release notes based on the latest git commit"
    required: false
  notifyTesters:
    description: "If true, send an email notification to the distribution group"
    required: false
  debug:
    description: "If true, shows additional information from the action execution"
    required: false
    default: false
branding:
  color: "red"
  icon: "send"
runs:
  using: "docker"
  image: "Dockerfile      
          echo Add other actions to build,
          echo test, and deploy your project.
